services:
  postgres-main:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-main-db-volume:/var/lib/postgresql/data
    restart: always

  minio:
    image: minio/minio:latest
    container_name: minio
    env_file:
      - .env
    ports:
      - "9000:9000"    
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    env_file:
      - .env
    volumes:
      - neo4j_volume:/var/lib/neo4j

volumes:
  postgres-main-db-volume:
  neo4j_volume:
  minio_data:
    driver: local

